repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: ['--allow-multiple-documents']
        exclude: 'helm/.*/templates/.*'
      - id: check-json
      - id: check-added-large-files
        args: ['--maxkb=2000']
      - id: check-merge-conflict

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.92.1
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
        args:
          - --hook-config=dir:terraform/environments/dev
      - id: terraform_trivy
        args:
          - --args=--severity HIGH,CRITICAL
      - id: terraform_checkov
        args:
          - --args=--framework terraform

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.4
    hooks:
      - id: gitleaks
