apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "devsecops-platform.fullname" . }}
  labels:
    app: {{ include "devsecops-platform.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "devsecops-platform.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "devsecops-platform.name" . }}
    spec:
      serviceAccountName: {{ include "devsecops-platform.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: app
          image: {{ include "devsecops-platform.image" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}

          {{- if .Values.configMap.enabled }}
          envFrom:
            - configMapRef:
                name: {{ include "devsecops-platform.fullname" . }}-config
          {{- end }}

          ports:
            - name: http
              containerPort: 8080
              protocol: TCP

          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.path }}
              port: http
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}

          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.path }}
              port: http
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}